### ISSUE TITLE
您好,可以增加对网站paypayfleamarket.yahoo.co.jp的支持吗

### ISSUE THREAD

**Issue by qz270777** [SpriteMisaka/Mercari-Notifier#1]
另外,可以增加关键词和商家屏蔽功能吗,求求啦.
可以给您100金钱支持.

**Comment by SpriteMisaka** [comment]
你好，现在已经增加了这些功能：

+ 可以获取 Yahoo!フリマ 的商品信息；
+ 可以在`settings.json`的`exclude`中设置关键词，当商品名包含任一时则屏蔽。

现在使用的接口没办法直接获得商家名称，因此实现商家屏蔽功能要先研究看看商品详情页。
课业繁忙，等空闲时再来捣鼓。

**Comment by qz270777** [comment]
我不会使用hook_url通知,  我使用的telegrambot通知,但是我发现仅mercari通知显示图片预览,其余两个网站有图片链接,但是并不显示图片,请问这是个例吗,hook_url会全部网站通知都显示图片吗?
另外,关键词屏蔽已经足够,等您空闲时再完善即可,您可以发送支付宝或微信收款码给我,我将给您一点点支持.

**Comment by SpriteMisaka** [comment]
稍微了解了一下，telegram貌似不能像discord一样处理embed message，而且，telegram bot可能因为安全问题无法处理某些网站的图片url。
因此我帮忙写了关于telegram的处理逻辑：先下载预览图片，再使用sendPhoto发送。现在你可以在`settings.json`中配置`telegram_token`和`telegram_chat_id`来使用telegram bot。我已经测试这样能够显示图片预览，下面是paypayfleamarket.yahoo.co.jp的一个例子。
![123055](https://github.com/user-attachments/assets/8afde7a6-2a89-43d6-bb4b-f77c8ecb0424)
至于我的收款码：
![3cd820fac93e08bb07a18f4bc9e7f79](https://github.com/user-attachments/assets/babf137d-7845-4861-8421-04f23d6b9c02)
![3375ca633a58887b5c6276697d92f78](https://github.com/user-attachments/assets/13bb6e6b-8f94-4581-b6cd-7e8490f42945)
感谢你的支持!
