### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by qz270777** [SpriteMisaka/Mercari-Notifier#2]
https://zenmarket.jp加了验证导致脚本运行失败吗?请问你可以正常运行嘛?

**Comment by SpriteMisaka** [comment]
他们换了一些东西，我有空再来看一下。

**Comment by SpriteMisaka** [comment]
已经修改好，现在改成了解析网页来抓取商品信息，你需要安装python的第三方库`beautifulsoup4`才能运行程序。
