### ISSUE TITLE
Keeps blocking on preprocessing items

### ISSUE THREAD

**Issue by yeeatalt** [SpriteMisaka/Mercari-Notifier#3]
Hi ,

Thanks for this notifier that is really helpful but since i updated my keywords, it seems to block on Preprocessing items, any help possible ?

**Comment by SpriteMisaka** [comment]
Hi,

I’m not sure what might be causing the issue. Could you please provide more details about how you modified `settings.json`?

**Comment by yeeatalt** [comment]
```
{
    "keywords": ["初音ミク フィギュア"],
    "discord_hook_url": "",
    "telegram_token": "772xxxxxxxxxxxxxxxxxxxxg",
    "telegram_chat_id": "76xxxxx0491",
	"proxies": {},
    "exclude": [""]
}
```

**Comment by SpriteMisaka** [comment]
> \> python start.py
2024-09-26 00:31:02 [INFO] Preprocessing items via keyword [初音ミク フィギュア]...
2024-09-26 00:31:34 [INFO] Done.

I didn't see any blocking issue...

If there is a "Done" ouput, it will provide feedback every hour during the day (system time 8:00 ~ 23:00 by default). If not, please check your network settings.

**Comment by SpriteMisaka** [comment]
Also, if you don’t want to exclude any products, the `exclude` field should be `[]`.

> "exclude": []

**Comment by yeeatalt** [comment]
Thanks a lot for your fast answers, managed to change my server and its now working !
